version: '3.4'


services:
 manager:
  image: censormanager:latest
  restart: always
 api:
  image: censorapi:latest
  restart: always
  ports:
   - 5000:80
  environment:
   - ASPNETCORE_blacklistUrl=http://manager
  depends_on:
   - manager